#!/bin/sh
# Copyright 2019-2020 Benjamin 'Benno' Falkner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation the 
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
# sell copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

cat <<EOF
edo-browser-kiosk
manage the edo-browser-kiosk

EOF

USER_NAME=edo-browser-kiosk
ENABLE=TRUE

help(){
    cat <<EOF
usage: edo-browser-kiosk <args>
    -u= --user=[user_name]          set the username of the browser-kiosk (default: $USER_NAME)
    -t= --target=[http location]    sets the http location for browser-kiosk
    --enable/--disable              browser-kiosk
EOF
}



for i in "$@"
do
case $i in
    -u=*|--user=*)
        USER_NAME="${i#*=}"
        shift 
    ;;
    -t=*|--target=*)
        TARGET="${i#*=}"
        shift 
    ;;
    --enable)
        ENABLE=TRUE
    shift 
    ;;
    --disable)
        ENABLE=FALSE
    shift 
    ;;
    *)
        # unknown option
    ;;
esac
done

USER_HOME=$(getent passwd $USER_NAME | cut -d: -f6)
test -z "$TARGET" || sed -i "s|SERVERNAME=.*|SERVERNAME=$TARGET|" $USER_HOME/.xinitrc 
TARGET=$(grep "SERVERNAME=" $USER_HOME/.xinitrc | cut -d\" -f2)
test "$ENABLE" = "FALSE" || systemctl enable getty@tty1.service
test "$ENABLE" = "TRUE" || systemctl disable getty@tty1.service


echo "User:           $USER_NAME"
echo "User Directory: $USER_HOME"
echo "Target:         $TARGET"
echo "Enabled:        $ENABLE"
